#!/bin/bash
addr=192.168.200.2
server=`grep '^nameserver\s' /etc/resolv.conf | awk 'NR==1{print $2}'`
gw=`netstat -nr | grep -E '^(default|0\.0\.0\.0)' | awk 'NR==1{print $2}'`
route add -host $server gw $gw
route delete default
bash <<< "sleep 3;ip r add default via $addr;exit" &
./client.py
route add -net 0.0.0.0 gw $gw
route delete -host $server
